/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/inline_6_engine.glb 
Author: 漂EZ-GAZI流 (https://sketchfab.com/EZ-GAZI)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/inline-6-engine-b819462500714069b6515ec95051c4e8
Title: INLINE 6 ENGINE
*/
import { useGLTF, Edges } from '@react-three/drei'
import { Wireframe } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'

export function Inline6(props) {
  const { nodes, materials } = useGLTF('/models/inline_6_engine.glb')

    const groupRef = useRef() // 3. Create a reference to the group

  // 4. Rotate the group on every frame
  useFrame((state, delta) => {
    if (groupRef.current) {
      groupRef.current.rotation.y += delta * 0.5 // Adjust 0.5 for speed
    }
  })
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-20, 100, 0]} rotation={[0, 0, -Math.PI / 6]} scale={[80, 80, 310]}>
          <mesh geometry={nodes.ENGINE_METAL_0.geometry} material={materials.METAL}>
             <Edges scale={1} threshold={10} color="black" />
          </mesh>
          <mesh geometry={nodes.ENGINE_PLASTIC_0.geometry} material={materials.PLASTIC} >
             <Edges scale={1} threshold={10} color="black" />
          </mesh>
          <mesh geometry={nodes.ENGINE_RUBBER_0.geometry} material={materials.RUBBER}>
            <Edges scale={1} threshold={10} color="black" />
          </mesh>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/inline_6_engine.glb')
